### ISSUE TITLE
Compatibility with CoffeeScript?

### ISSUE THREAD

**Issue by jonarrien** [sokolovstas/SublimeWebInspector#28] opened 2013-03-21 15:11 UTC
I would like to know if there is some way to use this plugin with coffeescript. As Ruby developer, i don't compile the source code into javascript until production deployment.

**Comment by m1sta** [comment] 2015-04-01 17:16
+1

**Comment by danmosemsft** [comment] 2015-06-11 04:08
Resolving as a duplicate of #55, which came later but has a more general title. It seems there is nothing specific here to CoffeeScript, that would not also apply to Typescript, etc. Essentially, source maps need to work.

**Closed by danmosemsft** 2015-06-11 04:08 UTC
Labels: enhancement
